[package]
name = "rost"
version = "0.1.0"
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
log = "0.4.22"
uefi = { version = "0.33.0", features = ["logger", "panic_handler"] }
