[package]
name = "rost"
version = "0.1.0"
edition = "2021"
default-run = "qemu-uefi"

[workspace]
members = [
    "kernel",
]

[dependencies]

[build-dependencies]
kernel = {path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }
bootloader = "0.11.9"

