[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
common = {path = "../common"}
log = "0.4.25"
linked_list_allocator = "0.10.5"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
