[package]
name = "bootloader"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.22"
common = {path = "../common"}
uefi = { version = "0.33.0", features = ["alloc", "logger", "panic_handler", "global_allocator"] }
